name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
        cd interpreter
        make
        cd ../ccompiler
        make
    # - name: make check
    #   run: make check
    # - name: make distcheck
    #   run: make distcheck
    - name: test brainfuck interpreter
      run: |
        cd interpreter
        ./bfi ../test/beer.bf
        ./bfi ../test/fibonacci.bf
        ./bfi ../test/hello_world.bf
        ./bfi ../test/simple.bf
    - name: test brainfuck c compiler
      run: |
        cd ccompiler
        ./bfcc ../test/beer.bf
        ./a.out
        ./bfcc ../test/fibonacci.bf
        ./a.out
        ./bfcc ../test/hello_world.bf
        ./a.out
        ./bfcc ../test/simple.bf
        ./a.out
        ./bfcc ../test/io.bf

